### PR TITLE
added queue to ftool

### PR DESCRIPTION
**Pull request by vincenzocarusotto**
- Added support to number of keys based on user input
- Changed ftool to be queue based to avoid key pressing overlap, now cast only a skill each loop

### CODE REVIEW

**Comment by ils94** [comment]
What is the idea behind your commit?

**Comment by ils94** [comment]
Tried your code, doesn't seem to work and also is making PyFlyff lag too.

**Comment by vincenzocarusotto** [comment]
> 

Fixed, now it should work

**Comment by vincenzocarusotto** [comment]
> What is the idea behind your commit?
-> No more use loop counter, just keep going till stop
-> No more use min interval
-> Now loop is evaluated each 1 + random.uniform(0, 1) seconds
-> Each loop enqueue elegible keys
-> Each loop execute a key if there is any in queue

The reason i changed it to a queue is for avoid to press multiple keys at the same moment
This way it will always execute the keys

**Comment by ils94** [comment]
> > What is the idea behind your commit?
> > -> No more use loop counter, just keep going till stop
> > -> No more use min interval
> > -> Now loop is evaluated each 1 + random.uniform(0, 1) seconds
> > -> Each loop enqueue elegible keys
> > -> Each loop execute a key if there is any in queue
> 
> The reason i changed it to a queue is for avoid to press multiple keys at the same moment This way it will always execute the keys

In the original code, you set the "fix loop" to yes, so it doesn't press multiple keys at the same moment.

The min interval have use too, as you can control when the key will be pressed this will just limit up to 1 second always with no options.

There is also a caveat I see with your code, it leaving behind unusable Threads that is decreasing performance.

But I get what you wanted to do here, looks nice, but you also have to understand my approach too with the original code.

Your code is also pressing multiple keys at the same time too, having the same problem I encountered when I added the "fix loop" option in the mini ftool config.

try to change:

```
def multithreading(function):
    threading.Thread(target=function).start()
```

to:

```
def multithreading(function):
    x = threading.Thread(target=function)
    x.setDaemon(True)
    x.start()
```
You can find this in miscs.py

and see if at least you can fix the thread (I should have made this change back in the day, sorry thats my fault :P)

After further testing,  really liked your code, just need to fix these issues I pointed:

The thread created for the loop seems to be making everything else lag on my computer at least
It still has the issue of pressing multiple keys (just test it, press the key to turn the ftool on and off then press it again and it will start to press multiple keys)

**Comment by vincenzocarusotto** [comment]
> > In the original code, you set the "fix loop" to yes, so it doesn't press multiple keys at the same moment.
> 
> The min interval have use too, as you can control when the key will be pressed this will just limit up to 1 second always with no options.
> 
> There is also a caveat I see with your code, it leaving behind unusable Threads that is decreasing performance.
> 
> But I get what you wanted to do here, looks nice, but you also have to understand my approach too with the original code.
> 
> Your code is also pressing multiple keys at the same time too, having the same problem I encountered when I added the "fix loop" option in the mini ftool config.
> 
> try to change:
> 
> ```
> def multithreading(function):
>     threading.Thread(target=function).start()
> ```
> 
> to:
> 
> ```
> def multithreading(function):
>     x = threading.Thread(target=function)
>     x.setDaemon(True)
>     x.start()
> ```
> 
> You can find this in miscs.py
> 
> and see if at least you can fix the thread (I should have made this change back in the day, sorry thats my fault :P)
> 
> After further testing, really liked your code, just need to fix these issues I pointed:
> 
> The thread created for the loop seems to be making everything else lag on my computer at least It still has the issue of pressing multiple keys (just test it, press the key to turn the ftool on and off then press it again and it will start to press multiple keys)

Fixed the thread spawning problem now it only use one thread, i don't know if there is a better place to initialize the ftool_loop thread

**Comment by ils94** [comment]
> > > > What is the idea behind your commit?
> > > > -> No more use loop counter, just keep going till stop
> > > > -> No more use min interval
> > > > -> Now loop is evaluated each 1 + random.uniform(0, 1) seconds
> > > > -> Each loop enqueue elegible keys
> > > > -> Each loop execute a key if there is any in queue
> > > 
> > > 
> > > The reason i changed it to a queue is for avoid to press multiple keys at the same moment This way it will always execute the keys
> > 
> > 
> > In the original code, you set the "fix loop" to yes, so it doesn't press multiple keys at the same moment.
> > The min interval have use too, as you can control when the key will be pressed this will just limit up to 1 second always with no options.
> > There is also a caveat I see with your code, it leaving behind unusable Threads that is decreasing performance.
> > But I get what you wanted to do here, looks nice, but you also have to understand my approach too with the original code.
> > Your code is also pressing multiple keys at the same time too, having the same problem I encountered when I added the "fix loop" option in the mini ftool config.
> > try to change:
> > ```
> > def multithreading(function):
> >     threading.Thread(target=function).start()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to:
> > ```
> > def multithreading(function):
> >     x = threading.Thread(target=function)
> >     x.setDaemon(True)
> >     x.start()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can find this in miscs.py
> > and see if at least you can fix the thread (I should have made this change back in the day, sorry thats my fault :P)
> > After further testing, really liked your code, just need to fix these issues I pointed:
> > The thread created for the loop seems to be making everything else lag on my computer at least It still has the issue of pressing multiple keys (just test it, press the key to turn the ftool on and off then press it again and it will start to press multiple keys)
> 
> Fixed the thread spawning problem now it only use one thread, i don't know if there is a better place to initialize the ftool_loop thread

My code already spawn a thread to deal with mini ftool loop

```
if not globalVariables.start_mini_ftool_loop:
            if globalVariables.mini_ftool_activation_key != "" and globals()["mini_ftool_in_game_key_1"] != "":
                globalVariables.start_mini_ftool_loop = True
                miscs.multithreading(self.mini_ftool_loop)
```

**Comment by vincenzocarusotto** [comment]
> 
> My code already spawn a thread to deal with mini ftool loop
> 
> ```
> if not globalVariables.start_mini_ftool_loop:
>             if globalVariables.mini_ftool_activation_key != "" and globals()["mini_ftool_in_game_key_1"] != "":
>                 globalVariables.start_mini_ftool_loop = True
>                 miscs.multithreading(self.mini_ftool_loop)
> ```
A the moment you spawn a thread each time you press the ON key, when you press OFF the thread will not exit immediatly, if you spam the key you will spawn multiple threads and they could keep living if you spam fast enough like ON->thread on time.wait -> OFF -> ON now you have 2 threads running. That way you only have one thread and there is no key press overlapping

**Comment by ils94** [comment]
> > 
> > My code already spawn a thread to deal with mini ftool loop
> > 
> > ```
> > if not globalVariables.start_mini_ftool_loop:
> >             if globalVariables.mini_ftool_activation_key != "" and globals()["mini_ftool_in_game_key_1"] != "":
> >                 globalVariables.start_mini_ftool_loop = True
> >                 miscs.multithreading(self.mini_ftool_loop)
> > ```
> A the moment you spawn a thread each time you press the ON key, when you press OFF the thread will not exit immediatly, if you spam the key you will spawn multiple threads and they could keep living if you spam fast enough like ON->thread on time.wait -> OFF -> ON now you have 2 threads running. That way you only have one thread and there is no key press overlapping
> 

In my code when you stop the mini ftool, the thread dies because the while loop also dies.

**Pull request closed without merging**
